trigger:
- main

pool: local

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Test_and_Build
    steps:
      - task: UseDotNet@2
        displayName: 'Select NET SDK version'
        inputs:
          version: 9.0.301
      - task: DotNetCoreCLI@2
        displayName: 'Restore Solution'
        inputs:
          command: restore
          projects: $(solution)

      - task: DotNetCoreCLI@2
        displayName: 'Run Unit Tests'
        inputs:
          command: test
